### PR TITLE
psram: modify from psram initialization demo of bouffalo-hal project

### PR DESCRIPTION
**Pull request by ZhengLongBing**
- Implemented the initialization of UHS PSRAM.

### CODE REVIEW

**Review by Placebo27 — CHANGES_REQUESTED** [review]
Please adhere the test results on M1s Dock board, need the screenshot of serial port output to prove initialize psram successfully, thx. 
And a suggested header is `psram: modify from psram initialization demo of bouffalo-hal project`.
Remember to add references in your commit message, you can follow this commit (https://github.com/rustsbi/bouffaloader/commit/3e089a9199368c4d2e2b856a4a23cf69b077e125).
In your commit message, it looks like `Refs: https://github.com/rustsbi/bouffalo-hal/blob/main/examples/peripherals/psram-demo/src/psram.rs`.

Please apply each suggestion to your future commits, maybe I should write a guideline.

**Comment by ZhengLongBing** [comment]
If you are willing to write a guide or provide relevant information, I will be very grateful.

**Review by Placebo27 — APPROVED** [review]

**Comment by Placebo27** [comment]
Here is my test result on M1s dock board, which proves initialize psram successfully, the serial port output is as follows: 

image

**Review by Placebo27 — CHANGES_REQUESTED** [review]
You need to combine multiple commits into one with `git rebase` command. 

Please refer to https://docs.github.com/en/get-started/using-git/using-git-rebase-on-the-command-line.

**Comment by ZhengLongBing** [comment]
I have combined multiple commits into one.Can you confirm it again?

**Review by Placebo27 — APPROVED** [review]

**Pull request merged**
